/**
 * Skill card catalog — the player's ridiculous hidden talents.
 *
 * Stats range 0–10. Tags are the matching vocabulary shared with
 * Position.requiredTags (see src/content/positions.ts).
 */
import type { SkillCard, SkillStats } from "../game/types";

/** Fill unspecified stats with 0 to keep the catalog readable. */
function s(partial: Partial<SkillStats>): SkillStats {
  return {
    logic: 0,
    confidence: 0,
    technical: 0,
    chaos: 0,
    corporate: 0,
    honesty: 0,
    schleim: 0,
    creativity: 0,
    ...partial,
  };
}

export const SKILLS: SkillCard[] = [
  {
    id: "serious-face",
    label: "I can look serious in meetings",
    description: "Nobody has ever caught me thinking about lunch.",
    hiddenTags: ["meetings", "presentation", "survival"],
    stats: s({ confidence: 6, corporate: 7, schleim: 3 }),
  },
  {
    id: "polite-to-ai",
    label: "I can ask ChatGPT without insulting it",
    description: "When the machines rise, I will be spared.",
    hiddenTags: ["ai", "prompting", "diplomacy"],
    stats: s({ technical: 5, honesty: 4, creativity: 4, schleim: 2 }),
  },
  {
    id: "excel-calm",
    label: "I can open Excel without sweating",
    description: "VLOOKUP holds no power over me. Mostly.",
    hiddenTags: ["excel", "data", "crisis"],
    stats: s({ logic: 6, technical: 6, confidence: 4 }),
  },
  {
    id: "roadmap-bluff",
    label: "I can say 'roadmap' when I mean 'I have no idea'",
    description: "Strategic ambiguity is still strategy.",
    hiddenTags: ["buzzword", "improvisation", "leadership"],
    stats: s({ corporate: 8, confidence: 6, schleim: 5, honesty: 0 }),
  },
  {
    id: "meeting-survivor",
    label: "I can survive a meeting that could have been an email",
    description: "Forty slides. No agenda. I lived.",
    hiddenTags: ["meetings", "survival", "patience"],
    stats: s({ corporate: 5, honesty: 3, confidence: 3, logic: 2 }),
  },
  {
    id: "reply-all-restraint",
    label: "I have never once hit Reply All by accident",
    description: "A flawless record. The whole company knows about Kevin's.",
    hiddenTags: ["email", "diplomacy", "survival"],
    stats: s({ logic: 5, corporate: 4, honesty: 5 }),
  },
  {
    id: "printer-whisperer",
    label: "I can fix the printer by staring at it",
    description: "It jams for others. For me, it behaves.",
    hiddenTags: ["printer", "technical", "crisis"],
    stats: s({ technical: 7, chaos: 3, confidence: 5 }),
  },
  {
    id: "deadline-negotiator",
    label: "I can call a missed deadline a 'timeline evolution'",
    description: "Nothing is late if the plan was 'directional'.",
    hiddenTags: ["buzzword", "deadline", "improvisation"],
    stats: s({ corporate: 7, creativity: 5, schleim: 4, honesty: 1 }),
  },
  {
    id: "coffee-diplomat",
    label: "I know exactly how the boss takes their coffee",
    description: "Oat milk. 60 degrees. Don't ask how I know.",
    hiddenTags: ["coffee", "flattery", "psychology"],
    stats: s({ schleim: 8, corporate: 3, confidence: 3 }),
  },
  {
    id: "nod-strategically",
    label: "I can nod at the exact right moment",
    description: "Comprehension optional. Timing impeccable.",
    hiddenTags: ["meetings", "flattery", "psychology"],
    stats: s({ schleim: 6, corporate: 5, confidence: 4 }),
  },
  {
    id: "powerpoint-alchemist",
    label: "I can turn three bullet points into forty slides",
    description: "Content is finite. Transitions are not.",
    hiddenTags: ["powerpoint", "presentation", "buzzword"],
    stats: s({ creativity: 7, corporate: 6, technical: 3, schleim: 3 }),
  },
  {
    id: "slide-shrinker",
    label: "I can turn forty slides back into three bullet points",
    description: "The rarer, more dangerous direction.",
    hiddenTags: ["powerpoint", "presentation", "logic"],
    stats: s({ logic: 8, honesty: 6, technical: 3 }),
  },
  {
    id: "jargon-fluent",
    label: "I am fluent in Corporate as a second language",
    description: "'Let's circle back' — and I never do.",
    hiddenTags: ["buzzword", "smalltalk", "diplomacy"],
    stats: s({ corporate: 9, schleim: 5, creativity: 3, honesty: 1 }),
  },
  {
    id: "mute-master",
    label: "I always know when I'm on mute",
    description: "A sixth sense. Some are born with it.",
    hiddenTags: ["meetings", "technical", "remote"],
    stats: s({ technical: 5, logic: 4, confidence: 3 }),
  },
  {
    id: "camera-ready",
    label: "I own one blazer for video calls",
    description: "Below the waist: pajamas. Above: quarterly-results energy.",
    hiddenTags: ["remote", "presentation", "improvisation"],
    stats: s({ confidence: 5, corporate: 4, creativity: 4, honesty: 3 }),
  },
  {
    id: "inbox-zero-liar",
    label: "I can claim Inbox Zero with 4,782 unread",
    description: "Zero is a mindset, not a number.",
    hiddenTags: ["email", "improvisation", "buzzword"],
    stats: s({ confidence: 6, chaos: 4, honesty: 0, corporate: 3 }),
  },
  {
    id: "ai-prompt-poet",
    label: "I can make an AI apologize to me",
    description: "Prompt engineering is just assertive politeness.",
    hiddenTags: ["ai", "prompting", "psychology"],
    stats: s({ technical: 6, creativity: 6, confidence: 5 }),
  },
  {
    id: "ai-detector",
    label: "I can tell when a colleague's email was written by AI",
    description: "'I hope this finds you well' — it never does, Greg.",
    hiddenTags: ["ai", "email", "psychology"],
    stats: s({ logic: 6, technical: 5, honesty: 5 }),
  },
  {
    id: "excel-archaeologist",
    label: "I can open a spreadsheet from 2009 without crying",
    description: "Merged cells. Hidden columns. Sheet3 (final) FINAL v2.",
    hiddenTags: ["excel", "data", "documentation"],
    stats: s({ technical: 7, logic: 6, honesty: 4 }),
  },
  {
    id: "pivot-table-shaman",
    label: "I can summon a pivot table on the first try",
    description: "Witnesses have wept.",
    hiddenTags: ["excel", "data", "technical"],
    stats: s({ technical: 8, logic: 7, confidence: 4 }),
  },
  {
    id: "vlookup-veteran",
    label: "I survived a VLOOKUP with 14 nested IFs",
    description: "The formula bar still appears in my dreams.",
    hiddenTags: ["excel", "crisis", "survival"],
    stats: s({ technical: 7, logic: 6, chaos: 2, honesty: 4 }),
  },
  {
    id: "calendar-tetris",
    label: "I can schedule a meeting for 11 people in one attempt",
    description: "Including the one who blocks 'focus time' all week.",
    hiddenTags: ["meetings", "logistics", "psychology"],
    stats: s({ logic: 7, corporate: 5, technical: 3 }),
  },
  {
    id: "agenda-enforcer",
    label: "I once ended a meeting early",
    description: "People still talk about it in hushed tones.",
    hiddenTags: ["meetings", "leadership", "crisis"],
    stats: s({ confidence: 8, logic: 5, honesty: 5, chaos: 2 }),
  },
  {
    id: "smalltalk-athlete",
    label: "I can discuss weather for 45 minutes",
    description: "Cloud cover is my Mona Lisa.",
    hiddenTags: ["smalltalk", "networking", "survival"],
    stats: s({ creativity: 4, corporate: 4, schleim: 4, confidence: 3 }),
  },
  {
    id: "linkedin-influencer",
    label: "I can write 'Agree?' at the end of a LinkedIn post",
    description: "Thought leadership is 90% punctuation.",
    hiddenTags: ["linkedin", "networking", "buzzword"],
    stats: s({ corporate: 6, schleim: 6, creativity: 4, confidence: 4 }),
  },
  {
    id: "humble-bragger",
    label: "I am humbled to announce literally anything",
    description: "So blessed. So grateful. So available for hire.",
    hiddenTags: ["linkedin", "flattery", "buzzword"],
    stats: s({ schleim: 7, corporate: 5, creativity: 3 }),
  },
  {
    id: "budget-illusionist",
    label: "I can make any number fit in a budget slide",
    description: "Rounding is an art form. Auditors disagree.",
    hiddenTags: ["budget", "data", "improvisation"],
    stats: s({ creativity: 6, chaos: 5, corporate: 5, honesty: 0 }),
  },
  {
    id: "expense-poet",
    label: "I can justify any expense as 'team building'",
    description: "The jacuzzi was a strategic alignment exercise.",
    hiddenTags: ["budget", "improvisation", "buzzword"],
    stats: s({ creativity: 7, chaos: 5, schleim: 3, honesty: 0 }),
  },
  {
    id: "crisis-face",
    label: "I stay calm when the demo breaks",
    description: "'This is actually a feature we're sunsetting.'",
    hiddenTags: ["crisis", "presentation", "improvisation"],
    stats: s({ confidence: 8, creativity: 6, chaos: 3, corporate: 3 }),
  },
  {
    id: "blame-router",
    label: "I can make 'whose fault is it' a team discussion",
    description: "Accountability is a journey, not a destination.",
    hiddenTags: ["diplomacy", "psychology", "survival"],
    stats: s({ corporate: 6, schleim: 5, creativity: 5, honesty: 1 }),
  },
  {
    id: "honest-estimator",
    label: "I say 'two weeks' and actually mean it",
    description: "The rarest skill in this entire deck.",
    hiddenTags: ["deadline", "honesty", "logic"],
    stats: s({ honesty: 9, logic: 6, confidence: 4 }),
  },
  {
    id: "documentation-monk",
    label: "I write documentation nobody asked for",
    description: "Someone will thank me in 2031.",
    hiddenTags: ["documentation", "technical", "honesty"],
    stats: s({ technical: 6, logic: 6, honesty: 7 }),
  },
  {
    id: "wifi-summoner",
    label: "I can find the one working conference-room HDMI cable",
    description: "It's labeled 'DO NOT REMOVE'. I removed it.",
    hiddenTags: ["technical", "crisis", "logistics"],
    stats: s({ technical: 6, chaos: 4, confidence: 4 }),
  },
  {
    id: "acronym-decoder",
    label: "I can pretend to know what the acronym means",
    description: "I'll look up 'EBITDA' right after this meeting. Again.",
    hiddenTags: ["buzzword", "improvisation", "survival"],
    stats: s({ corporate: 5, confidence: 5, chaos: 2, honesty: 1 }),
  },
  {
    id: "feedback-sandwich-chef",
    label: "I can criticize you so nicely you'll thank me",
    description: "Great energy! Everything's wrong. Love the font!",
    hiddenTags: ["diplomacy", "psychology", "leadership"],
    stats: s({ corporate: 6, schleim: 5, creativity: 4, honesty: 3 }),
  },
  {
    id: "notification-zen",
    label: "I can ignore 47 Slack pings during deep work",
    description: "@channel fears me.",
    hiddenTags: ["survival", "remote", "logic"],
    stats: s({ logic: 6, confidence: 5, honesty: 4, chaos: 2 }),
  },
  {
    id: "automation-gremlin",
    label: "I automated my status updates in 2022",
    description: "The bot has been 'making great progress' ever since.",
    hiddenTags: ["automation", "technical", "chaos"],
    stats: s({ technical: 8, chaos: 6, creativity: 6, honesty: 1 }),
  },
  {
    id: "macro-wizard",
    label: "I wrote a macro that does my colleague's job",
    description: "He doesn't know. He got promoted.",
    hiddenTags: ["automation", "excel", "technical"],
    stats: s({ technical: 9, logic: 7, chaos: 4, honesty: 2 }),
  },
  {
    id: "ctrl-z-reflexes",
    label: "My Ctrl+Z reflexes are faster than my regrets",
    description: "Undo history is my autobiography.",
    hiddenTags: ["technical", "crisis", "survival"],
    stats: s({ technical: 5, chaos: 3, honesty: 4, logic: 3 }),
  },
  {
    id: "meeting-parasite",
    label: "I can join any meeting and look essential",
    description: "'Just here to listen in' — for three years now.",
    hiddenTags: ["meetings", "survival", "improvisation"],
    stats: s({ schleim: 5, corporate: 5, chaos: 3, confidence: 4 }),
  },
  {
    id: "org-chart-navigator",
    label: "I know who actually makes decisions here",
    description: "Hint: it's Sandra from accounting. It's always Sandra.",
    hiddenTags: ["networking", "psychology", "leadership"],
    stats: s({ logic: 6, corporate: 6, honesty: 4, creativity: 3 }),
  },
  {
    id: "birthday-rememberer",
    label: "I remember every manager's birthday",
    description: "And their dog's. And their dog's gluten situation.",
    hiddenTags: ["flattery", "networking", "psychology"],
    stats: s({ schleim: 8, corporate: 3, creativity: 2 }),
  },
  {
    id: "compliment-sniper",
    label: "I can compliment a haircut that clearly went wrong",
    description: "'So bold. So you.' Flawless delivery.",
    hiddenTags: ["flattery", "diplomacy", "improvisation"],
    stats: s({ schleim: 8, creativity: 4, confidence: 4, honesty: 0 }),
  },
  {
    id: "laugh-on-cue",
    label: "I can laugh at the CEO's joke on the third retelling",
    description: "Each laugh more authentic than the last.",
    hiddenTags: ["flattery", "survival", "psychology"],
    stats: s({ schleim: 9, corporate: 4, confidence: 3, honesty: 0 }),
  },
  {
    id: "buzzword-bingo-champion",
    label: "I can use 'synergy' unironically",
    description: "Also 'leverage', 'holistic', and — forgive me — 'ideate'.",
    hiddenTags: ["buzzword", "presentation", "smalltalk"],
    stats: s({ corporate: 9, schleim: 6, creativity: 2, honesty: 0 }),
  },
  {
    id: "innovation-theater-director",
    label: "I can run a brainstorm where nothing gets decided",
    description: "Seventeen sticky notes. Zero outcomes. Standing ovation.",
    hiddenTags: ["innovation", "meetings", "buzzword"],
    stats: s({ creativity: 6, corporate: 7, chaos: 3, schleim: 3 }),
  },
  {
    id: "disruption-survivor",
    label: "I have survived four company 'transformations'",
    description: "Same job, four different titles, zero raises.",
    hiddenTags: ["survival", "innovation", "crisis"],
    stats: s({ honesty: 6, logic: 5, corporate: 5, confidence: 3 }),
  },
  {
    id: "intern-translator",
    label: "I can explain the company to interns without lying much",
    description: "'It's chaotic' covers most of the onboarding deck.",
    hiddenTags: ["leadership", "honesty", "documentation"],
    stats: s({ honesty: 7, logic: 5, creativity: 4 }),
  },
  {
    id: "ceo-mimic",
    label: "I can quote the CEO's keynote back at them",
    description: "'As you brilliantly said in Q3...' Devastating. Effective.",
    hiddenTags: ["flattery", "leadership", "psychology"],
    stats: s({ schleim: 9, corporate: 6, creativity: 3, honesty: 0 }),
  },
  {
    id: "elevator-pitcher",
    label: "I can pitch anything in one elevator ride",
    description: "Including why I was in the executive elevator.",
    hiddenTags: ["presentation", "improvisation", "networking"],
    stats: s({ confidence: 8, creativity: 6, corporate: 4, chaos: 2 }),
  },
  {
    id: "silence-wielder",
    label: "I can hold eye contact until the other person agrees",
    description: "HR has asked me to use this power responsibly.",
    hiddenTags: ["psychology", "leadership", "chaos"],
    stats: s({ confidence: 9, chaos: 4, honesty: 3 }),
  },
  {
    id: "task-juggler",
    label: "I can hold six 'top priorities' at once",
    description: "They're all number one. That's what makes them top.",
    hiddenTags: ["survival", "logistics", "deadline"],
    stats: s({ logic: 5, corporate: 5, chaos: 3, confidence: 4 }),
  },
  {
    id: "printer-sacrificer",
    label: "I know which intern to send to the printer",
    description: "Delegation is a leadership competency.",
    hiddenTags: ["delegation", "leadership", "printer"],
    stats: s({ corporate: 6, chaos: 3, schleim: 3, confidence: 4, honesty: 2 }),
  },
  {
    id: "lunch-strategist",
    label: "I can turn any lunch into a networking opportunity",
    description: "You came for the pasta. You left with three action items.",
    hiddenTags: ["networking", "smalltalk", "psychology"],
    stats: s({ corporate: 6, schleim: 4, creativity: 4, confidence: 5 }),
  },
  {
    id: "prompt-librarian",
    label: "I keep a spreadsheet of my best AI prompts",
    description: "Tab 1: prompts. Tab 2: prompts about prompts.",
    hiddenTags: ["ai", "prompting", "excel", "documentation"],
    stats: s({ technical: 7, logic: 6, creativity: 5, honesty: 4 }),
  },
  {
    id: "ai-apologizer",
    label: "I can blame the AI and get away with it",
    description: "'The model hallucinated' is the new 'the dog ate it'.",
    hiddenTags: ["ai", "improvisation", "survival"],
    stats: s({ chaos: 5, creativity: 5, corporate: 4, honesty: 0, confidence: 4 }),
  },
  {
    id: "workflow-archaeologist",
    label: "I can find why the process takes 14 approvals",
    description: "Step 9 exists because of an incident in 2014. Nobody remembers it.",
    hiddenTags: ["automation", "documentation", "logic"],
    stats: s({ logic: 8, technical: 5, honesty: 6, corporate: 3 }),
  },
  {
    id: "shortcut-dealer",
    label: "I know keyboard shortcuts that scare people",
    description: "I once Alt+Tabbed and a director gasped.",
    hiddenTags: ["technical", "excel", "automation"],
    stats: s({ technical: 8, confidence: 4, logic: 5 }),
  },
  {
    id: "chair-warmer",
    label: "I can radiate productivity while doing nothing",
    description: "Furrowed brow. Occasional sigh. Typing sounds optional.",
    hiddenTags: ["survival", "improvisation", "chaos"],
    stats: s({ chaos: 5, confidence: 5, schleim: 4, honesty: 0 }),
  },
  {
    id: "overtime-marty",
    label: "I visibly stay 10 minutes after the boss leaves",
    description: "Dedication is a performance art.",
    hiddenTags: ["flattery", "survival", "psychology"],
    stats: s({ schleim: 7, corporate: 4, honesty: 1, confidence: 2 }),
  },
  {
    id: "water-cooler-oracle",
    label: "I hear every rumor 48 hours early",
    description: "The reorg? I knew before the org did.",
    hiddenTags: ["networking", "psychology", "smalltalk"],
    stats: s({ logic: 4, creativity: 3, chaos: 3, corporate: 4, honesty: 3 }),
  },
  {
    id: "template-hoarder",
    label: "I have a template for every possible email",
    description: "Including 'apology for sending the wrong template'.",
    hiddenTags: ["email", "documentation", "automation"],
    stats: s({ logic: 6, technical: 5, corporate: 5, honesty: 4 }),
  },
  {
    id: "deck-necromancer",
    label: "I can resurrect any old deck as 'new strategy'",
    description: "Change the year, invert the arrow, ship it.",
    hiddenTags: ["powerpoint", "improvisation", "buzzword"],
    stats: s({ creativity: 6, chaos: 4, corporate: 6, honesty: 0 }),
  },
  {
    id: "meeting-escape-artist",
    label: "I can leave a meeting without anyone noticing",
    description: "'I have a hard stop' — the magic words.",
    hiddenTags: ["meetings", "survival", "improvisation"],
    stats: s({ chaos: 4, confidence: 5, logic: 4, honesty: 2 }),
  },
  {
    id: "kpi-poet",
    label: "I can make any metric look like growth",
    description: "Down 40%? That's 'a 60% retention of momentum'.",
    hiddenTags: ["data", "buzzword", "presentation"],
    stats: s({ creativity: 7, corporate: 7, chaos: 3, honesty: 0, logic: 3 }),
  },
  {
    id: "quiet-fixer",
    label: "I fix things quietly before anyone panics",
    description: "You've never heard of my greatest achievements. That's the point.",
    hiddenTags: ["crisis", "technical", "honesty"],
    stats: s({ technical: 7, logic: 7, honesty: 7, confidence: 3 }),
  },
  {
    id: "escalation-poker",
    label: "I know exactly when to CC someone's manager",
    description: "A weapon of last resort. I resort to it weekly.",
    hiddenTags: ["email", "psychology", "chaos"],
    stats: s({ chaos: 6, corporate: 5, confidence: 5, honesty: 2 }),
  },
  {
    id: "onboarding-veteran",
    label: "I can find the coffee machine on day one",
    description: "Also the good bathroom. Priorities.",
    hiddenTags: ["coffee", "logistics", "survival"],
    stats: s({ logic: 4, honesty: 5, creativity: 3, confidence: 3 }),
  },
];
